version: '3.8'

services:
  agent:
    build: "./"
    image: agent-syspad
    container_name: agent-container
    ports:
      - "3000:3000"
    networks:
      - syspad-network
    restart: always


volumes:
  syspad-database: {}

networks:
  syspad-network: